// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetStore.Api.Data;

#nullable disable

namespace PetStore.Api.Data.Migrations.Pets
{
    [DbContext(typeof(PetStoreContext))]
    partial class PetStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PetStore.Api.Entities.Pets.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PetTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PetTypeId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(2024, 10, 1),
                            Name = "Chuchi",
                            PetTypeId = 2,
                            Price = 200.50m
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateOnly(2024, 9, 15),
                            Name = "Chuchu",
                            PetTypeId = 2,
                            Price = 180.75m
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateOnly(2023, 11, 5),
                            Name = "Vuevue",
                            PetTypeId = 2,
                            Price = 350.00m
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateOnly(2025, 1, 20),
                            Name = "Ungang",
                            PetTypeId = 2,
                            Price = 90.00m
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateOnly(2024, 12, 30),
                            Name = "Jaya",
                            PetTypeId = 1,
                            Price = 215.25m
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateOnly(2023, 8, 10),
                            Name = "Trisha",
                            PetTypeId = 1,
                            Price = 120.10m
                        });
                });

            modelBuilder.Entity("PetStore.Api.Entities.Pets.PetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dog"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cat"
                        });
                });

            modelBuilder.Entity("PetStore.Api.Entities.Pets.Pet", b =>
                {
                    b.HasOne("PetStore.Api.Entities.Pets.PetType", "Type")
                        .WithMany()
                        .HasForeignKey("PetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });
#pragma warning restore 612, 618
        }
    }
}
