// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetStore.Api.Data;

#nullable disable

namespace PetStore.Api.Data.Migrations.Foods
{
    [DbContext(typeof(FoodStoreContext))]
    partial class FoodStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PetStore.Api.Entities.Foods.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoodTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoodTypeId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FoodTypeId = 1,
                            Name = "Beef Biscuits",
                            Price = 10.50m
                        },
                        new
                        {
                            Id = 2,
                            FoodTypeId = 1,
                            Name = "Chicken Nuggets",
                            Price = 8.75m
                        },
                        new
                        {
                            Id = 3,
                            FoodTypeId = 2,
                            Name = "Thin Tuna Cuts",
                            Price = 5.25m
                        },
                        new
                        {
                            Id = 4,
                            FoodTypeId = 3,
                            Name = "Apple Crunch",
                            Price = 6.00m
                        },
                        new
                        {
                            Id = 5,
                            FoodTypeId = 4,
                            Name = "Goat Milk",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 6,
                            FoodTypeId = 2,
                            Name = "Fish Jerky",
                            Price = 9.40m
                        });
                });

            modelBuilder.Entity("PetStore.Api.Entities.Foods.FoodType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FoodTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Meat"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fish"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Snack"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Drink"
                        });
                });

            modelBuilder.Entity("PetStore.Api.Entities.Foods.Food", b =>
                {
                    b.HasOne("PetStore.Api.Entities.Foods.FoodType", "FoodTypes")
                        .WithMany()
                        .HasForeignKey("FoodTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
