// 🐾 PETS API

### Get all pets
GET http://localhost:5036/pets

###

### Get pet by ID
GET http://localhost:5036/pets/3

###

### Create new pet
POST http://localhost:5036/pets
Content-Type: application/json

{
    "name" : "tanjiro",
    "PetTypeId": 2,
    "price": 5.50,
    "birthDate": "2024-12-30"
}

###

### Verify pets
GET http://localhost:5036/pets

###
PUT http://localhost:5036/pets/6
Content-Type: application/json

{
    "name": "Jaya",
    "petType": "Dog",
    "price": 20.32,
    "birthDate": "2025-10-03"
}

###
DELETE http://localhost:5036/pets/7
// 🍖 FOODS API

### Get all foods
GET http://localhost:5036/foods

###

### Get food by ID
GET http://localhost:5036/foods/4

###

### Create new food
POST http://localhost:5036/foods
Content-Type: application/json

{
    "foodName": "CornBeef",
    "FoodTypeId": 1,
    "foodPrice": 12.22
}

###

### Verify foods
GET http://localhost:5036/foods

###
Put http://localhost:5036/foods/3
Content-Type: application/json

{
    "foodName": "Goat Milk",
    "foodType": "Drinks",
    "foodPrice": 10.11
}

###
DELETE http://localhost:5036/foods/3